// To parse this JSON data, do
//
//     final adverseDRsReportConfirmationList = adverseDRsReportConfirmationListFromJson(jsonString);

import 'dart:convert';

List<AdverseDRsReportConfirmationList> adverseDRsReportConfirmationListFromJson(String str) => List<AdverseDRsReportConfirmationList>.from(json.decode(str).map((x) => AdverseDRsReportConfirmationList.fromJson(x)));

String adverseDRsReportConfirmationListToJson(List<AdverseDRsReportConfirmationList> data) => json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class AdverseDRsReportConfirmationList {
  int reportId;
  String reportTitle;
  String reportOn;
  String reportType;
  String productCategory;
  String institutionName;
  int institutionContact;
  String institutionFacilityCode;
  String institutionCounty;
  String patientInitials;
  String patientIpOpNo;
  String dateOfBirthAge;
  String patientAddress;
  String patientWardClinic;
  String gender;
  String anyKnownAllergies;
  String pregnancyStatus;
  dynamic patientWeight;
  int patientHeight;
  DateTime onsetDateOfAdrs;
  String descriptionOfAdrs;
  String medicalHistory;
  String currentMedicine1;
  bool suspected1;
  String drugBrand1;
  String batchLotno1;
  String manufacturer1;
  String dose1;
  String route1;
  String frequency1;
  String rxStartDate1;
  String rxEndDate1;
  String indication1;
  String currentMedicine2;
  bool suspected2;
  String drugBrand2;
  String batchLotno2;
  String manufacturer2;
  String dose2;
  String route2;
  String frequency2;
  String rxStartDate2;
  String rxEndDate2;
  String indication2;
  String currentMedicine3;
  bool suspected3;
  String drugBrand3;
  String batchLotno3;
  String manufacturer3;
  String dose3;
  String route3;
  String frequency3;
  String rxStartDate3;
  String rxEndDate3;
  String indication3;
  String currentMedicine4;
  bool suspected4;
  String drugBrand4;
  String batchLotno4;
  String manufacturer4;
  String dose4;
  String route4;
  String frequency4;
  String rxStartDate4;
  String rxEndDate4;
  String indication4;
  String currentMedicine5;
  bool suspected5;
  String drugBrand5;
  String batchLotno5;
  String manufacturer5;
  String dose5;
  String route5;
  String frequency5;
  String rxStartDate5;
  String rxEndDate5;
  String indication5;
  String pastMedicineHx1;
  String drugBrandHx1;
  String batchLotnoHx1;
  String manufacturerHx1;
  String doseHx1;
  String routeHx1;
  String frequencyHx1;
  String rxStartDateHx1;
  String rxEndDateHx1;
  String indicationHx1;
  String pastMedicineHx2;
  String drugBrandHx2;
  String batchLotnoHx2;
  String manufacturerHx2;
  String doseHx2;
  String routeHx2;
  String frequencyHx2;
  String rxStartDateHx2;
  String rxEndDateHx2;
  String indicationHx2;
  String pastMedicineHx3;
  String drugBrandHx3;
  String batchLotnoHx3;
  String manufacturerHx3;
  String doseHx3;
  String routeHx3;
  String frequencyHx3;
  String rxStartDateHx3;
  String rxEndDateHx3;
  String indicationHx3;
  String pastMedicineHx4;
  String drugBrandHx4;
  String batchLotnoHx4;
  String manufacturerHx4;
  String doseHx4;
  String routeHx4;
  String frequencyHx4;
  String rxStartDateHx4;
  String rxEndDateHx4;
  String indicationHx4;
  String pastMedicineHx5;
  String drugBrandHx5;
  String batchLotnoHx5;
  String manufacturerHx5;
  String doseHx5;
  String routeHx5;
  String frequencyHx5;
  String rxStartDateHx5;
  String rxEndDateHx5;
  String indicationHx5;
  String adrsHaltResolution;
  String adrsResumeResolution;
  String labInvestigationReport;
  String adrsGrading1;
  String adrsGrading2;
  String adrsGrading3;
  String adrsGrading4;
  String adrsGrading5;
  String otherComments;
  String reporterDetailsFirstName;
  String reporterDetailsOtherNames;
  String reporterDetailsCadreDesignation;
  int reporterDetailsMobileNo;
  String reporterDetailsEmail;
  String dateOfReport;
  String adrsReportStatus;

  AdverseDRsReportConfirmationList({
    required this.reportId,
    required this.reportTitle,
    required this.reportOn,
    required this.reportType,
    required this.productCategory,
    required this.institutionName,
    required this.institutionContact,
    required this.institutionFacilityCode,
    required this.institutionCounty,
    required this.patientInitials,
    required this.patientIpOpNo,
    required this.dateOfBirthAge,
    required this.patientAddress,
    required this.patientWardClinic,
    required this.gender,
    required this.anyKnownAllergies,
    required this.pregnancyStatus,
    required this.patientWeight,
    required this.patientHeight,
    required this.onsetDateOfAdrs,
    required this.descriptionOfAdrs,
    required this.medicalHistory,
    required this.currentMedicine1,
    required this.suspected1,
    required this.drugBrand1,
    required this.batchLotno1,
    required this.manufacturer1,
    required this.dose1,
    required this.route1,
    required this.frequency1,
    required this.rxStartDate1,
    required this.rxEndDate1,
    required this.indication1,
    required this.currentMedicine2,
    required this.suspected2,
    required this.drugBrand2,
    required this.batchLotno2,
    required this.manufacturer2,
    required this.dose2,
    required this.route2,
    required this.frequency2,
    required this.rxStartDate2,
    required this.rxEndDate2,
    required this.indication2,
    required this.currentMedicine3,
    required this.suspected3,
    required this.drugBrand3,
    required this.batchLotno3,
    required this.manufacturer3,
    required this.dose3,
    required this.route3,
    required this.frequency3,
    required this.rxStartDate3,
    required this.rxEndDate3,
    required this.indication3,
    required this.currentMedicine4,
    required this.suspected4,
    required this.drugBrand4,
    required this.batchLotno4,
    required this.manufacturer4,
    required this.dose4,
    required this.route4,
    required this.frequency4,
    required this.rxStartDate4,
    required this.rxEndDate4,
    required this.indication4,
    required this.currentMedicine5,
    required this.suspected5,
    required this.drugBrand5,
    required this.batchLotno5,
    required this.manufacturer5,
    required this.dose5,
    required this.route5,
    required this.frequency5,
    required this.rxStartDate5,
    required this.rxEndDate5,
    required this.indication5,
    required this.pastMedicineHx1,
    required this.drugBrandHx1,
    required this.batchLotnoHx1,
    required this.manufacturerHx1,
    required this.doseHx1,
    required this.routeHx1,
    required this.frequencyHx1,
    required this.rxStartDateHx1,
    required this.rxEndDateHx1,
    required this.indicationHx1,
    required this.pastMedicineHx2,
    required this.drugBrandHx2,
    required this.batchLotnoHx2,
    required this.manufacturerHx2,
    required this.doseHx2,
    required this.routeHx2,
    required this.frequencyHx2,
    required this.rxStartDateHx2,
    required this.rxEndDateHx2,
    required this.indicationHx2,
    required this.pastMedicineHx3,
    required this.drugBrandHx3,
    required this.batchLotnoHx3,
    required this.manufacturerHx3,
    required this.doseHx3,
    required this.routeHx3,
    required this.frequencyHx3,
    required this.rxStartDateHx3,
    required this.rxEndDateHx3,
    required this.indicationHx3,
    required this.pastMedicineHx4,
    required this.drugBrandHx4,
    required this.batchLotnoHx4,
    required this.manufacturerHx4,
    required this.doseHx4,
    required this.routeHx4,
    required this.frequencyHx4,
    required this.rxStartDateHx4,
    required this.rxEndDateHx4,
    required this.indicationHx4,
    required this.pastMedicineHx5,
    required this.drugBrandHx5,
    required this.batchLotnoHx5,
    required this.manufacturerHx5,
    required this.doseHx5,
    required this.routeHx5,
    required this.frequencyHx5,
    required this.rxStartDateHx5,
    required this.rxEndDateHx5,
    required this.indicationHx5,
    required this.adrsHaltResolution,
    required this.adrsResumeResolution,
    required this.labInvestigationReport,
    required this.adrsGrading1,
    required this.adrsGrading2,
    required this.adrsGrading3,
    required this.adrsGrading4,
    required this.adrsGrading5,
    required this.otherComments,
    required this.reporterDetailsFirstName,
    required this.reporterDetailsOtherNames,
    required this.reporterDetailsCadreDesignation,
    required this.reporterDetailsMobileNo,
    required this.reporterDetailsEmail,
    required this.dateOfReport,
    required this.adrsReportStatus,
  });

  factory AdverseDRsReportConfirmationList.fromJson(Map<String, dynamic> json) => AdverseDRsReportConfirmationList(
    reportId: json["reportId"],
    reportTitle: json["reportTitle"],
    reportOn: json["reportOn"],
    reportType: json["reportType"],
    productCategory: json["productCategory"],
    institutionName: json["institutionName"],
    institutionContact: json["institutionContact"],
    institutionFacilityCode: json["institutionFacilityCode"],
    institutionCounty: json["institutionCounty"],
    patientInitials: json["patientInitials"],
    patientIpOpNo: json["patientIpOpNo"],
    dateOfBirthAge: json["dateOfBirthAge"],
    patientAddress: json["patientAddress"],
    patientWardClinic: json["patientWardClinic"],
    gender: json["gender"],
    anyKnownAllergies: json["anyKnownAllergies"],
    pregnancyStatus: json["pregnancyStatus"],
    patientWeight: json["patientWeight"],
    patientHeight: json["patientHeight"],
    onsetDateOfAdrs: DateTime.parse(json["onsetDateOfAdrs"]),
    descriptionOfAdrs: json["descriptionOfAdrs"],
    medicalHistory: json["medicalHistory"],
    currentMedicine1: json["currentMedicine_1"],
    suspected1: json["suspected_1"],
    drugBrand1: json["drugBrand_1"],
    batchLotno1: json["batchLotno_1"],
    manufacturer1: json["manufacturer_1"],
    dose1: json["dose_1"],
    route1: json["route_1"],
    frequency1: json["frequency_1"],
    rxStartDate1: json["rxStartDate_1"],
    rxEndDate1: json["rxEndDate_1 "],
    indication1: json["indication_1"],
    currentMedicine2: json["currentMedicine_2"],
    suspected2: json["suspected_2"],
    drugBrand2: json["drugBrand_2"],
    batchLotno2: json["batchLotno_2"],
    manufacturer2: json["manufacturer_2"],
    dose2: json["dose_2"],
    route2: json["route_2"],
    frequency2: json["frequency_2"],
    rxStartDate2: json["rxStartDate_2"],
    rxEndDate2: json["rxEndDate_2"],
    indication2: json["indication_2"],
    currentMedicine3: json["currentMedicine_3"],
    suspected3: json["suspected_3"],
    drugBrand3: json["drugBrand_3"],
    batchLotno3: json["batchLotno_3"],
    manufacturer3: json["manufacturer_3"],
    dose3: json["dose_3"],
    route3: json["route_3"],
    frequency3: json["frequency_3"],
    rxStartDate3: json["rxStartDate_3"],
    rxEndDate3: json["rxEndDate_3"],
    indication3: json["indication_3"],
    currentMedicine4: json["currentMedicine_4"],
    suspected4: json["suspected_4"],
    drugBrand4: json["drugBrand_4"],
    batchLotno4: json["batchLotno_4"],
    manufacturer4: json["manufacturer_4"],
    dose4: json["dose_4"],
    route4: json["route_4"],
    frequency4: json["frequency_4"],
    rxStartDate4: json["rxStartDate_4"],
    rxEndDate4: json["rxEndDate_4"],
    indication4: json["indication_4"],
    currentMedicine5: json["currentMedicine_5"],
    suspected5: json["suspected_5"],
    drugBrand5: json["drugBrand_5"],
    batchLotno5: json["batchLotno_5"],
    manufacturer5: json["manufacturer_5"],
    dose5: json["dose_5"],
    route5: json["route_5"],
    frequency5: json["frequency_5"],
    rxStartDate5: json["rxStartDate_5"],
    rxEndDate5: json["rxEndDate_5"],
    indication5: json["indication_5"],
    pastMedicineHx1: json["pastMedicineHx_1"],
    drugBrandHx1: json["drugBrandHx_1"],
    batchLotnoHx1: json["batchLotnoHx_1"],
    manufacturerHx1: json["manufacturerHx_1"],
    doseHx1: json["doseHx_1"],
    routeHx1: json["routeHx_1"],
    frequencyHx1: json["frequencyHx_1"],
    rxStartDateHx1: json["rxStartDateHx_1"],
    rxEndDateHx1: json["rxEndDateHx_1"],
    indicationHx1: json["indicationHx_1"],
    pastMedicineHx2: json["pastMedicineHx_2"],
    drugBrandHx2: json["drugBrandHx_2"],
    batchLotnoHx2: json["batchLotnoHx_2"],
    manufacturerHx2: json["manufacturerHx_2"],
    doseHx2: json["doseHx_2"],
    routeHx2: json["routeHx_2"],
    frequencyHx2: json["frequencyHx_2"],
    rxStartDateHx2: json["rxStartDateHx_2"],
    rxEndDateHx2: json["rxEndDateHx_2"],
    indicationHx2: json["indicationHx_2"],
    pastMedicineHx3: json["pastMedicineHx_3"],
    drugBrandHx3: json["drugBrandHx_3"],
    batchLotnoHx3: json["batchLotnoHx_3"],
    manufacturerHx3: json["manufacturerHx_3"],
    doseHx3: json["doseHx_3"],
    routeHx3: json["routeHx_3"],
    frequencyHx3: json["frequencyHx_3"],
    rxStartDateHx3: json["rxStartDateHx_3"],
    rxEndDateHx3: json["rxEndDateHx_3"],
    indicationHx3: json["indicationHx_3"],
    pastMedicineHx4: json["pastMedicineHx_4"],
    drugBrandHx4: json["drugBrandHx_4"],
    batchLotnoHx4: json["batchLotnoHx_4"],
    manufacturerHx4: json["manufacturerHx_4"],
    doseHx4: json["doseHx_4"],
    routeHx4: json["routeHx_4"],
    frequencyHx4: json["frequencyHx_4"],
    rxStartDateHx4: json["rxStartDateHx_4"],
    rxEndDateHx4: json["rxEndDateHx_4"],
    indicationHx4: json["indicationHx_4"],
    pastMedicineHx5: json["pastMedicineHx_5"],
    drugBrandHx5: json["drugBrandHx_5"],
    batchLotnoHx5: json["batchLotnoHx_5"],
    manufacturerHx5: json["manufacturerHx_5"],
    doseHx5: json["doseHx_5"],
    routeHx5: json["routeHx_5"],
    frequencyHx5: json["frequencyHx_5"],
    rxStartDateHx5: json["rxStartDateHx_5"],
    rxEndDateHx5: json["rxEndDateHx_5"],
    indicationHx5: json["indicationHx_5"],
    adrsHaltResolution: json["adrsHaltResolution"],
    adrsResumeResolution: json["adrsResumeResolution"],
    labInvestigationReport: json["labInvestigationReport"],
    adrsGrading1: json["adrsGrading_1"],
    adrsGrading2: json["adrsGrading_2"],
    adrsGrading3: json["adrsGrading_3"],
    adrsGrading4: json["adrsGrading_4"],
    adrsGrading5: json["adrsGrading_5"],
    otherComments: json["otherComments"],
    reporterDetailsFirstName: json["reporterDetailsFirstName"],
    reporterDetailsOtherNames: json["reporterDetailsOtherNames"],
    reporterDetailsCadreDesignation: json["reporterDetailsCadreDesignation"],
    reporterDetailsMobileNo: json["reporterDetailsMobileNo"],
    reporterDetailsEmail: json["reporterDetailsEmail"],
    dateOfReport: json["dateOfReport"],
    adrsReportStatus: json["adrsReportStatus"],
  );

  Map<String, dynamic> toJson() => {
    "reportId": reportId,
    "reportTitle": reportTitle,
    "reportOn": reportOn,
    "reportType": reportType,
    "productCategory": productCategory,
    "institutionName": institutionName,
    "institutionContact": institutionContact,
    "institutionFacilityCode": institutionFacilityCode,
    "institutionCounty": institutionCounty,
    "patientInitials": patientInitials,
    "patientIpOpNo": patientIpOpNo,
    "dateOfBirthAge": dateOfBirthAge,
    "patientAddress": patientAddress,
    "patientWardClinic": patientWardClinic,
    "gender": gender,
    "anyKnownAllergies": anyKnownAllergies,
    "pregnancyStatus": pregnancyStatus,
    "patientWeight": patientWeight,
    "patientHeight": patientHeight,
    "onsetDateOfAdrs": onsetDateOfAdrs.toIso8601String(),
    "descriptionOfAdrs": descriptionOfAdrs,
    "medicalHistory": medicalHistory,
    "currentMedicine_1": currentMedicine1,
    "suspected_1": suspected1,
    "drugBrand_1": drugBrand1,
    "batchLotno_1": batchLotno1,
    "manufacturer_1": manufacturer1,
    "dose_1": dose1,
    "route_1": route1,
    "frequency_1": frequency1,
    "rxStartDate_1": rxStartDate1,
    "rxEndDate_1 ": rxEndDate1,
    "indication_1": indication1,
    "currentMedicine_2": currentMedicine2,
    "suspected_2": suspected2,
    "drugBrand_2": drugBrand2,
    "batchLotno_2": batchLotno2,
    "manufacturer_2": manufacturer2,
    "dose_2": dose2,
    "route_2": route2,
    "frequency_2": frequency2,
    "rxStartDate_2": rxStartDate2,
    "rxEndDate_2": rxEndDate2,
    "indication_2": indication2,
    "currentMedicine_3": currentMedicine3,
    "suspected_3": suspected3,
    "drugBrand_3": drugBrand3,
    "batchLotno_3": batchLotno3,
    "manufacturer_3": manufacturer3,
    "dose_3": dose3,
    "route_3": route3,
    "frequency_3": frequency3,
    "rxStartDate_3": rxStartDate3,
    "rxEndDate_3": rxEndDate3,
    "indication_3": indication3,
    "currentMedicine_4": currentMedicine4,
    "suspected_4": suspected4,
    "drugBrand_4": drugBrand4,
    "batchLotno_4": batchLotno4,
    "manufacturer_4": manufacturer4,
    "dose_4": dose4,
    "route_4": route4,
    "frequency_4": frequency4,
    "rxStartDate_4": rxStartDate4,
    "rxEndDate_4": rxEndDate4,
    "indication_4": indication4,
    "currentMedicine_5": currentMedicine5,
    "suspected_5": suspected5,
    "drugBrand_5": drugBrand5,
    "batchLotno_5": batchLotno5,
    "manufacturer_5": manufacturer5,
    "dose_5": dose5,
    "route_5": route5,
    "frequency_5": frequency5,
    "rxStartDate_5": rxStartDate5,
    "rxEndDate_5": rxEndDate5,
    "indication_5": indication5,
    "pastMedicineHx_1": pastMedicineHx1,
    "drugBrandHx_1": drugBrandHx1,
    "batchLotnoHx_1": batchLotnoHx1,
    "manufacturerHx_1": manufacturerHx1,
    "doseHx_1": doseHx1,
    "routeHx_1": routeHx1,
    "frequencyHx_1": frequencyHx1,
    "rxStartDateHx_1": rxStartDateHx1,
    "rxEndDateHx_1": rxEndDateHx1,
    "indicationHx_1": indicationHx1,
    "pastMedicineHx_2": pastMedicineHx2,
    "drugBrandHx_2": drugBrandHx2,
    "batchLotnoHx_2": batchLotnoHx2,
    "manufacturerHx_2": manufacturerHx2,
    "doseHx_2": doseHx2,
    "routeHx_2": routeHx2,
    "frequencyHx_2": frequencyHx2,
    "rxStartDateHx_2": rxStartDateHx2,
    "rxEndDateHx_2": rxEndDateHx2,
    "indicationHx_2": indicationHx2,
    "pastMedicineHx_3": pastMedicineHx3,
    "drugBrandHx_3": drugBrandHx3,
    "batchLotnoHx_3": batchLotnoHx3,
    "manufacturerHx_3": manufacturerHx3,
    "doseHx_3": doseHx3,
    "routeHx_3": routeHx3,
    "frequencyHx_3": frequencyHx3,
    "rxStartDateHx_3": rxStartDateHx3,
    "rxEndDateHx_3": rxEndDateHx3,
    "indicationHx_3": indicationHx3,
    "pastMedicineHx_4": pastMedicineHx4,
    "drugBrandHx_4": drugBrandHx4,
    "batchLotnoHx_4": batchLotnoHx4,
    "manufacturerHx_4": manufacturerHx4,
    "doseHx_4": doseHx4,
    "routeHx_4": routeHx4,
    "frequencyHx_4": frequencyHx4,
    "rxStartDateHx_4": rxStartDateHx4,
    "rxEndDateHx_4": rxEndDateHx4,
    "indicationHx_4": indicationHx4,
    "pastMedicineHx_5": pastMedicineHx5,
    "drugBrandHx_5": drugBrandHx5,
    "batchLotnoHx_5": batchLotnoHx5,
    "manufacturerHx_5": manufacturerHx5,
    "doseHx_5": doseHx5,
    "routeHx_5": routeHx5,
    "frequencyHx_5": frequencyHx5,
    "rxStartDateHx_5": rxStartDateHx5,
    "rxEndDateHx_5": rxEndDateHx5,
    "indicationHx_5": indicationHx5,
    "adrsHaltResolution": adrsHaltResolution,
    "adrsResumeResolution": adrsResumeResolution,
    "labInvestigationReport": labInvestigationReport,
    "adrsGrading_1": adrsGrading1,
    "adrsGrading_2": adrsGrading2,
    "adrsGrading_3": adrsGrading3,
    "adrsGrading_4": adrsGrading4,
    "adrsGrading_5": adrsGrading5,
    "otherComments": otherComments,
    "reporterDetailsFirstName": reporterDetailsFirstName,
    "reporterDetailsOtherNames": reporterDetailsOtherNames,
    "reporterDetailsCadreDesignation": reporterDetailsCadreDesignation,
    "reporterDetailsMobileNo": reporterDetailsMobileNo,
    "reporterDetailsEmail": reporterDetailsEmail,
    "dateOfReport": dateOfReport,
    "adrsReportStatus": adrsReportStatus,
  };
}
